### ISSUE TITLE
Icon vanishing problem while moving multiple players

### ISSUE THREAD

**Issue by lssac7778** [utilForever/baba-is-auto#34]
Hello, I implemented "off limits" map and tested it, but when I move player after rule 'wall is you' is created, some walls are vanishing (shown in gif). I think there is problem when walls are overlaped.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/31644153/171997830-22e0748c-234c-48f0-88f8-af44aee32e3a.gif)
.

**Comment by utilForever** [comment]
@lssac7778 Thanks to report the bug! Can you send "off limits" map data? 🌞

**Comment by lssac7778** [comment]
Here it is. <off_limits.txt> is original map and <off_limits_bug.txt> is map that starts with 'wall is you' rule, which I made to reproduce the bug.
[off_limits.txt](https://github.com/utilForever/baba-is-auto/files/8837860/off_limits.txt)
[off_limits_bug.txt](https://github.com/utilForever/baba-is-auto/files/8837861/off_limits_bug.txt)
