### ISSUE TITLE
Rule does not working while moving multiple players

### ISSUE THREAD

**Issue by lssac7778** [utilForever/baba-is-auto#38]
In 'off limits' map, game is not win when reach flag with multiple players. Also, The wall doesn't disapper when it overlaped with skull.
![172533522-e99f53f8-d6ab-45be-afaa-a0b8108c66b9](https://user-images.githubusercontent.com/31644153/172534748-e0ef80df-fc33-42b6-b668-47a5c671340b.gif)

**Comment by utilForever** [comment]
@lssac7778 Thanks to report the bug! 😂

**Comment by lssac7778** [comment]
BTW, there is another small bug, walls are not overlaped when walls are stacked at the end of the map. In Baba is you game, when I play same map, the stacked walls moves like a single block
![bug3](https://user-images.githubusercontent.com/31644153/172770860-5eb064e7-7189-46ca-99fe-fd5541afe406.gif)
.

**Comment by utilForever** [comment]
> BTW, there is another small bug, walls are not overlaped when walls are stacked at the end of the map. In Baba is you game, when I play same map, the stacked walls moves like a single block. But they spreads out here. ![bug3](https://user-images.githubusercontent.com/31644153/172770860-5eb064e7-7189-46ca-99fe-fd5541afe406.gif) [ ](https://user-images.githubusercontent.com/31644153/172770860-5eb064e7-7189-46ca-99fe-fd5541afe406.gif) ![bug3](https://user-images.githubusercontent.com/31644153/172770860-5eb064e7-7189-46ca-99fe-fd5541afe406.gif) [ ](https://user-images.githubusercontent.com/31644153/172770860-5eb064e7-7189-46ca-99fe-fd5541afe406.gif) .

@Issac7778 Can you add another issue for it? Thanks.

**Comment by utilForever** [comment]
> In 'off limits' map, game is not win when reach flag with multiple players. Also, The wall doesn't disapper when it overlaped with skull. ![172533522-e99f53f8-d6ab-45be-afaa-a0b8108c66b9](https://user-images.githubusercontent.com/31644153/172534748-e0ef80df-fc33-42b6-b668-47a5c671340b.gif) [ ](https://user-images.githubusercontent.com/31644153/172534748-e0ef80df-fc33-42b6-b668-47a5c671340b.gif) ![172533522-e99f53f8-d6ab-45be-afaa-a0b8108c66b9](https://user-images.githubusercontent.com/31644153/172534748-e0ef80df-fc33-42b6-b668-47a5c671340b.gif) [ ](https://user-images.githubusercontent.com/31644153/172534748-e0ef80df-fc33-42b6-b668-47a5c671340b.gif)

1. In 'off limits' map, game is not win when reach flag with multiple players.
-> It's not a bug. "FLAG" is WIN and "FLAG_ICON" is WIN are not same. Please check your map data.
2. Also, The wall doesn't disapper when it overlaped with skull.
-> It's a bug. I'll fix it soon in an hour. 🗡️

**Comment by lssac7778** [comment]
> 
Sorry, that's my mistake. Thanks
