### ISSUE TITLE
Icons spread when they are stacked at the end of map

### ISSUE THREAD

**Issue by lssac7778** [utilForever/baba-is-auto#41]
In 'off limits' map, walls are not overlapped when walls are stacked at the end of the map. In original "Baba is you" game, when I play the same map, the stacked walls move like a single block. But they spread out here.

![172770860-5eb064e7-7189-46ca-99fe-fd5541afe406](https://user-images.githubusercontent.com/31644153/172784380-f51b2ed0-3a96-4af7-b9fa-25740f50faf2.gif)

**Comment by utilForever** [comment]
@lssac7778 Thanks to report the bug! 😂
